services:
  api-gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: betterReads.ApiGateway/betterReads.ApiGateway.Web/Dockerfile
    ports: 
      - "5000:5000"
  auth:
    image: auth
    build:
      context: .
      dockerfile: betterReads.Auth/betterReads.Auth.Web/Dockerfile
    ports: 
      - "5001:5001"
  books:
    image: books
    build: ./BetterReads.Books/BetterReads.Books.Web
    ports: 
      - "5002:5002"
  recommendations:
    image: recommendations
    build: ./BetterReads.Recommendations/BetterReads.Recommendations.Web
    ports: 
      - "5003:5003"
  reviews:
    image: reviews
    build: ./BetterReads.Reviews/BetterReads.Reviews.Web
    ports: 
      - "5004:5004"
  shelves:
    image: shelves
    build:
      context: .
      dockerfile: betterReads.Shelves/betterReads.Shelves.Web/Dockerfile
    ports: 
      - "5005:5005"