apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec: 
      containers:
        - name: auth
          image: betterreadsregistry.azurecr.io/auth:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 5001
      imagePullSecrets:
        - name: regcred
