apiVersion: v1
kind: Service
metadata:
  name: recommendations
  labels:
    app: recommendations
spec:
  ports:
    - port: 5003
      targetPort: 5003
  selector:
    app: recommendations
  type: ClusterIP
