name: Build and Push Docker Images

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure CLI Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push images
        run: |
          docker compose -f docker-compose-azure.yml build
          docker compose -f docker-compose-azure.yml push
