name: Build and Push Docker Images

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run .NET Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./BetterReads.Shelves/BetterReads.Shelves.Web/BetterReads.Shelves.Web.csproj

      - name: Build solution
        run: dotnet build ./BetterReads.Shelves/BetterReads.Shelves.Web/BetterReads.Shelves.Web.csproj --no-restore --configuration Release

      - name: Run integration tests
        run: dotnet test ./BetterReads.Shelves/BetterReads.Shelves.Tests/BetterReads.Shelves.Tests.csproj --configuration Release --verbosity normal
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure CLI Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push images
        run: |
          docker compose -f docker-compose-azure.yml build
          docker compose -f docker-compose-azure.yml push
